### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'tuple' and 'tuple'

### ISSUE THREAD

**Issue by jaquense** [MatthewVerbryke/gazebo_terrain#2]
Hi,

I'm getting this error:

Traceback (most recent call last):
  File "image_resize.py", line 116, in <module>
    main()
  File "image_resize.py", line 106, in main
    rescale_and_resize(img_name, img_size)
  File "image_resize.py", line 47, in rescale_and_resize
    scale_factor = 255.0/(img_max - img_min)
TypeError: unsupported operand type(s) for -: 'tuple' and 'tuple'

Best,

**Comment by MatthewVerbryke** [comment]
Hello,

Sorry for the late reply (still somewhat figuring out GitHub).

IIRC from my own experience, the error you're getting suggests that the PNG you're trying to use for the height-map may have an alpha channel or something similar in it. When the code is determining `img_max` and `img_min`, it's looking through each of the pixels in the image to determine their value, which should be represented as an integer. The equation to determine the `scale_factor` won't work if the pixel values are not integers, as your error is telling you. 

In order to get your image to work, I believe you will need to remove the alpha channel (or similar) from the PNG. You can find instructions online to do this in your image editor of choice.

**Comment by MatthewVerbryke** [comment]
Since its been half a year, I'm going close the issue for now. I believe what I've said in the above statement is likely the source of your problem.
